name             'consul-cluster'
maintainer       'Adam Krone'
maintainer_email 'adam.krone@thirdwavellc.com'
license          'Apache v2.0'
description      'Installs/Configures consul-cluster'
long_description 'Installs/Configures consul-cluster'
version          '0.1.0'

depends 'consul'
depends 'consul-services'
