name             'consul-cluster'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures consul-cluster'
long_description 'Installs/Configures consul-cluster'
version          '0.1.0'

depends 'consul'
depends 'consul-services'
